// <auto-generated />
namespace ProductManage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class pro_app : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pro_app));
        
        string IMigrationMetadata.Id
        {
            get { return "202305021134207_pro_app"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
